provisionerName: "rawfile.csi.openebs.io"

defaults: &defaults
  image:
    repository: docker.io/openebs/rawfile-localpv
    tag: 0.8.0
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

controller:
  <<: *defaults
  csiDriverArgs:
    - csi-driver
    - --disable-metrics

node:
  <<: *defaults
  storage:
    path: /var/csi/rawfile
  metrics:
    enabled: false

imagePullSecrets: []
serviceMonitor:
  enabled: true
  interval: 1m
