provisionerName: "rawfile.csi.openebs.io"

defaults: &defaults
  image:
    repository: docker.io/openebs/rawfile-localpv
    tag: 0.8.0
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

controller:
  <<: *defaults
  csiDriverArgs:
    - csi-driver
    - --disable-metrics

csiImages:
  repository: registry.k8s.io/sig-storage
  csiProvisioner:
    image: csi-provisioner
    tag: v5.0.1
  csiResizer:
    image: csi-resizer
    tag: v1.11.1
  csiSnapshotter:
    image: csi-snapshotter
    tag: v8.0.1
  nodeDriverRegistrar:
    image: csi-node-driver-registrar
    tag: v2.10.1

node:
  <<: *defaults
  storage:
    path: /var/csi/rawfile
  metrics:
    enabled: false

storageClass:
  enabled: false
  name: "csi-rawfile-default"
  isDefault: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

imagePullSecrets: []
serviceMonitor:
  enabled: true
  interval: 1m
