provisionerName: "rawfile.csi.openebs.io"

defaults: &defaults
  image:
    repository: docker.io/openebs/rawfile-localpv
    tag: 0.8.0
    pullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 100Mi

controller:
  <<: *defaults

node:
  <<: *defaults
  metrics:
    enabled: false

storageClass:
  enabled: false
  name: "csi-rawfile-default"
  isDefault: true

imagePullSecrets: []
serviceMonitor:
  enabled: true
  interval: 1m
