apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.provisionerName }}
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  storageCapacity: false  # TODO: reenable once switch from using v1beta1 apis
  volumeLifecycleModes:
    - Persistent
