name: cla-check
on:
  schedule:
    - cron: "0 0 * * *" # todo revert

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
