name: Synchronize CSI Images

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
jobs:
  synchronize:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Skopeo Sync
      run: |
        docker run -v ${GITHUB_WORKSPACE}:/tmp/ quay.io/skopeo/stable:v1.15 sync \
            --src yaml \
            --dest docker \
            /tmp/.github/data/sync-csi-images-config.yaml ghcr.io/canonical/sig-storage \
            --format oci \
            --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}