name: TICS Analysis

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/tics.yaml
  schedule:
    - cron: '0 10 * * 0'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    permissions:
      contents: read
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]

    steps:
      - name: Checking out repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          # pylint and flake8 are required by TICSQServer.
          pip install pylint flake8

          sudo apt install -y libbtrfsutil-dev
          pip wheel -w wheels/ "https://github.com/kdave/btrfs-progs/archive/refs/tags/v6.3.2.tar.gz#egg=btrfsutil&subdirectory=libbtrfsutil/python"
          pip install wheels/*
          pip install -r requirements.txt

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Install staticcheck
        run: |
          set -x

          # We don't have any unit tests for this project, but TICS expects this folder to exist.
          mkdir -p cover

          # Install staticcheck
          go install honnef.co/go/tools/cmd/staticcheck@v0.5.1

      - name: Run TICS
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: ${{ github.event.repository.name }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
